spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/biblioteca
    username: postgres
    password: post1234
    driver-class-name: org.postgresql.Driver
    
  flyway:
    enabled: true
    baseline-on-migrate: true

  jpa:
    hibernate:
      ddl-auto: update    # em produção, prefira 'validate' e migrations com Flyway
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

logging:
  level:
    com.projeto.pos.biblioteca.spring: ERROR
  file:
    name: logs/erro.log
  pattern:
    file: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# logging:
#   level:
#     org.hibernate.SQL: DEBUG
#     org.hibernate.type.descriptor.sql.BasicBinder: TRACE
